version: '3.4'

services:
  devcontainer:
    environment:
      - DISPLAY=${LOCAL_DISPLAY}
      - XAUTHORITY=${LOCAL_XAUTHORITY}
    volumes:
      - ${HOME}/.ssh:/home/devuser/.ssh:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${LOCAL_XAUTHORITY}:/home/devuser/.Xauthority:rw
